leagues = ["Albania: Superliga",
        "Argentina: Superliga",
        "Armenia: Premier League",
        "Australia: A-League",
        "Austria: Bundesliga",
        "Azerbaijan: Premier League",
        "Belarus: Premier League",
        "Brazil: Serie A",
        "Bulgaria: First League",
        "China: Super league",
        "Colombia: Primera A",
        "Cyprus: Division 1",
        "Czech Republic: 1. Liga",
        "Denmark: Superligaen",
        "Egypt: Division 1",
        "England: Championship",
        "England: Premier League",
        "Finland: Veikkausliiga",
        "France: Ligue 1",
        "France: Ligue 2",
        "Germany: Bundesliga",
        "Germany: Bundesliga II",
        "Greece: Super League",
        "Iceland: Premier League",
        "Iran: Pro League",
        "Italy: Serie A",
        "Italy: Serie B",
        "Kazakhstan: Premier League",
        "Netherlands: Eredivisie",
        "Nigeria: Premier League",
        "Norway: Eliteserien",
        "Poland: Ekstraklasa",
        "Poland: I-Liga",
        "Portugal: Liga NOS",
        "Romania: Liga I",
        "Russia: Football National League",
        "Russia: Premier League",
        "Scotland: Premiership",
        "Serbia: Super Liga",
        "Slovakia: Superliga",
        "Spain: La Liga",
        "Spain: LaLiga 2",
        "Sweden: Allsvenskan",
        "Sweden: Superettan",
        "Switzerland: Challenge League",
        "Switzerland: Super League",
        "Turkey: Super Lig",
        "Ukraine: Premier League",
        "Wales: Premier League"]
